server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:local;INIT=CREATE SCHEMA IF NOT EXISTS garage
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-dev.xml
    default-schema: garage

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: redis