server:
  port: 8082

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: redis