server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem;"INIT=CREATE SCHEMA IF NOT EXISTS GARAGE"
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
