DROP TABLE IF EXISTS garage.car;
DROP TABLE IF EXISTS garage.owner;

CREATE TABLE garage.owner
(
    owner_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(25) NOT NULL,
    last_name VARCHAR(25) NOT NULL ,
    gender VARCHAR(25) NOT NULL ,
    age integer NOT NULL ,
    CONSTRAINT "PK_owner_owner_id" PRIMARY KEY (owner_id)
);


CREATE TABLE garage.car
(
    car_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand VARCHAR(35) NOT NULL,
    model VARCHAR(25) NOT NULL,
    color VARCHAR(25) NOT NULL,
    type VARCHAR(10) NOT NULL,
    owner_id integer,
    CONSTRAINT PK_car_car_id PRIMARY KEY (car_id),
    CONSTRAINT FK_owner_owner_id FOREIGN KEY (owner_id) REFERENCES garage.owner(owner_id) ON DELETE CASCADE
);

INSERT INTO garage.owner(first_name,last_name,gender,age)
VALUES  ('Alex','Zdorvich','man',27),
        ('Vova','Zilvova','man',34),
        ('Arash','Batista','man',40),
        ('Said','Vondermayer','man',67);

INSERT INTO garage.car(brand,model,color,type,owner_id)
VALUES  ('MAZDA','CX9','RED','SUV',1),
        ('MAZDA','CX5','RED','SUV',1),
        ('MAZDA','CX3','WHITE','SUV',1),
        ('MAZDA','CX30','BLACK','SEDAN',2),
        ('TOYOTA','AURIS','BLACK','SEDAN',3),
        ('TOYOTA','HIGHLANDER','YELLOW','SUV',2),
        ('AUDI','RS6','RED','SEDAN',4),
        ('AUDI','Q8','BLACK','SUV',4),
        ('ACURA','ILX','BLACK','SEDAN',4),
        ('TOYOTA','CAMRY','BLACK','SEDAN',4)